server:
  port: 8080


spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.104:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
      username: root
      password: a13699770386bb
  data:
    mongodb:
      uri: mongodb://localhost:27017/aa


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo

logging:
  level:
    com:
      enoyor:
        DEBUG
    org:
      mybatis:
        info