server:
  port: 8081
#  servlet:
#    context-path: /njm1/test1/


spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.2.210:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT
      username: root
      password: a13699770386bb
  data:
    mongodb:
      uri: mongodb://192.168.2.210:27017/aa
#  mvc:
#    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo

logging:
  level:
    com:
      enoyor:
        DEBUG
    org:
      mybatis:
        info